# Generated by Django 3.2.6 on 2021-08-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N/A', 'Rather not say')], default='N/A', max_length=3)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.TextField(max_length=1000)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
