# Generated by Django 3.2.6 on 2021-08-25 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_student_header_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='header_image',
            new_name='image',
        ),
    ]
