# Generated by Django 3.2.6 on 2021-08-26 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_header_image_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
